### ISSUE TITLE
Do not request resource from classloader using path with leading slash

### ISSUE THREAD

**Issue by nuteee** [JetBrains/spotbugs-intellij-plugin#105]
```

Product Infos
    SpotBugs: 4.1.3
    IntelliJ SpotBugs plugin: 1.2.4
    IDEA: IntelliJ IDEA 2021.2
    IDEA-Build: IU-212.4746.92, July 27, 2021
    JRE: 11.0.11+9-b1504.13 x86_64
    JVM: OpenJDK 64-Bit Server VM JetBrains s.r.o.

Do not request resource from classloader using path with leading slash
com.intellij.diagnostic.PluginException: /messages_en_HU.xml [Plugin: org.jetbrains.plugins.spotbugs]
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:504)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:471)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
	at edu.umd.cs.findbugs.PluginLoader.getResource(PluginLoader.java:560)
	at edu.umd.cs.findbugs.PluginLoader.addCollection(PluginLoader.java:1279)
	at edu.umd.cs.findbugs.PluginLoader.getMessageDocuments(PluginLoader.java:1187)
	at edu.umd.cs.findbugs.PluginLoader.init(PluginLoader.java:690)
	at edu.umd.cs.findbugs.PluginLoader.<init>(PluginLoader.java:395)
	at edu.umd.cs.findbugs.PluginLoader.loadCorePlugin(PluginLoader.java:1442)
	at edu.umd.cs.findbugs.PluginLoader.loadInitialPlugins(PluginLoader.java:1396)
	at edu.umd.cs.findbugs.PluginLoader.<clinit>(PluginLoader.java:149)
	at edu.umd.cs.findbugs.DetectorFactoryCollection.getCoreResource(DetectorFactoryCollection.java:353)
	at edu.umd.cs.findbugs.SystemProperties.loadPropertiesFromConfigFile(SystemProperties.java:84)
	at edu.umd.cs.findbugs.SystemProperties.<clinit>(SystemProperties.java:67)
	at edu.umd.cs.findbugs.Project.<clinit>(Project.java:863)
	at org.jetbrains.plugins.spotbugs.core.FindBugsProjects.lambda$get$0(FindBugsProjects.java:129)
	at org.jetbrains.plugins.spotbugs.common.util.WithPluginClassloader.notNull(WithPluginClassloader.java:58)
	at org.jetbrains.plugins.spotbugs.core.FindBugsProjects.get(FindBugsProjects.java:129)
	at org.jetbrains.plugins.spotbugs.core.FindBugsProjects.addFile(FindBugsProjects.java:119)
	at org.jetbrains.plugins.spotbugs.core.FindBugsProjects.addFiles(FindBugsProjects.java:68)
	at org.jetbrains.plugins.spotbugs.core.FindBugsCompileAfterHook$2.configure(FindBugsCompileAfterHook.java:160)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.lambda$asyncStartImpl$3(FindBugsStarter.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:841)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.asyncStartImpl(FindBugsStarter.java:201)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.asyncStart(FindBugsStarter.java:191)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.access$000(FindBugsStarter.java:54)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter$2.run(FindBugsStarter.java:175)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by twogee** [comment]
Duplicate of #100
