### ISSUE TITLE
ResourceNotFoundException: Resource not found: java/lang/Object.class

### ISSUE THREAD

**Issue by jonnybbb** [JetBrains/spotbugs-intellij-plugin#14]
Product Infos
    SpotBugs: 4.0.0
    IntelliJ SpotBugs plugin: 1.1.0
    IDEA: IntelliJ IDEA 2020.1
    IDEA-Build: IU-201.6668.121, April 8, 2020
    JRE: 11.0.6+8-b765.25 x86_64
    JVM: OpenJDK 64-Bit Server VM JetBrains s.r.o

java.io.IOException: IOException while scanning codebases
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:311)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.executeImpl(FindBugsStarter.java:324)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.asyncStartImpl(FindBugsStarter.java:214)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.asyncStart(FindBugsStarter.java:191)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter$2.run(FindBugsStarter.java:175)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:930)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:432)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: edu.umd.cs.findbugs.classfile.ResourceNotFoundException: Resource not found: java/lang/Object.class
	at edu.umd.cs.findbugs.classfile.impl.ClassPathImpl.lookupResource(ClassPathImpl.java:162)
	at edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.build(ClassPathBuilder.java:282)
	at edu.umd.cs.findbugs.FindBugs2.buildClassPath(FindBugs2.java:708)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:245)
	... 17 more

**Comment by amaembo** [comment]
Please provide a minimal project where the problem appears. Thanks.

**Comment by windmeup** [comment]
IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 30, 2020

Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2000M
Cores: 4
Non-Bundled Plugins: GLSL, Mongo Plugin, CheckStyle-IDEA, Lombook Plugin, org.jetbrains.plugins.spotbugs, mobi.hsz.idea.gitignore, io.protostuff.protostuff-jetbrains-plugin, org.intellij.scala

IntelliJ SpotBugs plugin: 1.1.1

java.io.IOException: IOException while scanning codebases
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:311)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.executeImpl(FindBugsStarter.java:324)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.asyncStartImpl(FindBugsStarter.java:214)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.asyncStart(FindBugsStarter.java:191)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter$1.run(FindBugsStarter.java:168)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:932)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:482)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:77)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: edu.umd.cs.findbugs.classfile.ResourceNotFoundException: Resource not found: java/lang/Object.class
	at edu.umd.cs.findbugs.classfile.impl.ClassPathImpl.lookupResource(ClassPathImpl.java:162)
	at edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.build(ClassPathBuilder.java:282)
	at edu.umd.cs.findbugs.FindBugs2.buildClassPath(FindBugs2.java:708)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:245)
	... 18 more

**Comment by roturnd** [comment]
When I use "Analyze Scope Files" and choose the whole project, the same exception is thrown. Then I delete the "build" folder and choose "Analyze Project Files Including Test Sources" , it finished successfully.
