### ISSUE TITLE
com.intellij.diagnostic.PluginException: 314 ms to call on EDT PreviewSelectBugInstance#update@mouse shortcut (org.jetbrains.plugins.spotbugs.actions.PreviewSelectBugInstance). Revise AnAction.getActionUpdateThread property [Plugin: org.jetbrains.plugins.spotbugs] at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)

### ISSUE THREAD

**Issue by shilohooo** [JetBrains/spotbugs-intellij-plugin#1425]
The error was copied to the clipboard. Press Ctrl+V

**Comment by shilohooo** [comment]
Product Infos
    SpotBugs: 4.4.2
    IntelliJ SpotBugs plugin: 1.2.5
    IDEA: IntelliJ IDEA 2023.2.1
    IDEA-Build: IU-232.9559.62, August 23, 2023
    JRE: 17.0.8+7-b1000.8 amd64
    JVM: OpenJDK 64-Bit Server VM JetBrains s.r.o.

null
com.intellij.diagnostic.PluginException: 314 ms to call on EDT PreviewSelectBugInstance#update@mouse shortcut (org.jetbrains.plugins.spotbugs.actions.PreviewSelectBugInstance). Revise AnAction.getActionUpdateThread property [Plugin: org.jetbrains.plugins.spotbugs]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.computeOnEdt(ActionUpdater.java:261)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:212)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:170)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:146)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:132)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:725)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$UpdateSessionImpl.presentation(ActionUpdater.java:828)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doUpdateActionsInner(IdeKeyEventDispatcher.kt:832)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.access$doUpdateActionsInner(IdeKeyEventDispatcher.kt:1)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$processAction$chosenPair$1$chosen$2.invoke(IdeKeyEventDispatcher.kt:557)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$processAction$chosenPair$1$chosen$2.invoke(IdeKeyEventDispatcher.kt:548)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction$lambda$3$lambda$2(IdeKeyEventDispatcher.kt:556)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$15(Utils.java:804)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$19(ActionUpdater.java:435)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:431)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$16(Utils.java:804)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$18(Utils.java:811)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$20(Utils.java:810)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Throwable: EDT-trace-at-290-ms (2/5)
		at java.desktop/sun.font.FileFontStrike._getGlyphImageFromWindows(Native Method)
		at java.desktop/sun.font.FileFontStrike.getGlyphImageFromWindows(FileFontStrike.java:410)
		at java.desktop/sun.font.FileFontStrike.getGlyphImageFromNative(FileFontStrike.java:357)
		at java.desktop/sun.font.FileFontStrike.getGlyphImagePtr(FileFontStrike.java:456)
		at java.desktop/sun.font.FileFontStrike.getGlyphAdvance(FileFontStrike.java:762)
		at java.desktop/sun.font.FileFontStrike.getGlyphAdvance(FileFontStrike.java:673)
		at java.desktop/sun.font.CompositeStrike.getGlyphAdvance(CompositeStrike.java:149)
		at java.desktop/sun.font.CompositeStrike.getCodePointAdvance(CompositeStrike.java:160)
		at java.desktop/sun.font.FontDesignMetrics.handleCharWidth(FontDesignMetrics.java:420)
		at java.desktop/sun.font.FontDesignMetrics.getLatinCharWidth(FontDesignMetrics.java:429)
		at java.desktop/sun.font.FontDesignMetrics.stringWidth(FontDesignMetrics.java:480)
		at java.desktop/sun.swing.SwingUtilities2.getFontStringWidth(SwingUtilities2.java:939)
		at java.desktop/sun.swing.SwingUtilities2.stringWidth(SwingUtilities2.java:404)
		at java.desktop/sun.swing.SwingUtilities2.stringWidth(SwingUtilities2.java:374)
		at java.desktop/javax.swing.SwingUtilities.layoutCompoundLabelImpl(SwingUtilities.java:1133)
		at java.desktop/javax.swing.SwingUtilities.layoutCompoundLabel(SwingUtilities.java:1004)
		at java.desktop/javax.swing.plaf.basic.BasicLabelUI.layoutCL(BasicLabelUI.java:108)
		at com.intellij.ide.ui.laf.darcula.ui.DarculaLabelUI.layoutCL(DarculaLabelUI.java:94)
		at java.desktop/javax.swing.plaf.basic.BasicLabelUI.getPreferredSize(BasicLabelUI.java:262)
		at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1721)
		at com.intellij.openapi.wm.impl.content.TabContentLayout.layout(TabContentLayout.java:154)
		at com.intellij.openapi.wm.impl.content.SingleContentLayout.layout(SingleContentLayout.kt:237)
		at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.update(ToolWindowContentUi.java:348)
		at com.intellij.openapi.wm.impl.content.ToolWindowContentUi$1.selectionChanged(ToolWindowContentUi.java:206)
		at jdk.internal.reflect.GeneratedMethodAccessor233.invoke(Unknown Source)
		at java.base@17.0.8/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:568)
		at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:118)
		at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:83)
		at com.intellij.util.EventDispatcher$$Lambda$451/0x000000080055f808.invoke(Unknown Source)
		at jdk.proxy2/jdk.proxy2.$Proxy188.selectionChanged(Unknown Source)
		at com.intellij.ui.content.impl.ContentManagerImpl.fireSelectionChanged(ContentManagerImpl.java:621)
		at com.intellij.ui.content.impl.ContentManagerImpl.addSelectedContent(ContentManagerImpl.java:432)
		at com.intellij.ui.content.impl.ContentManagerImpl$2.run(ContentManagerImpl.java:520)
		at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContent(ContentManagerImpl.java:536)
		at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:485)
		at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:475)
		at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:559)
		at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContent(ContentManagerImpl.java:564)
		at com.intellij.ui.content.impl.ContentManagerImpl.doAddContent(ContentManagerImpl.java:201)
		at com.intellij.ui.content.impl.ContentManagerImpl.addContent(ContentManagerImpl.java:171)
		at org.jetbrains.plugins.spotbugs.core.ToolWindowFactoryImpl.createToolWindowContent(ToolWindowFactoryImpl.java:33)
		at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:554)
		at com.intellij.openapi.wm.impl.ToolWindowImpl.getContentManager(ToolWindowImpl.kt:423)
		at org.jetbrains.plugins.spotbugs.gui.toolwindow.view.ToolWindowPanel.getInstance(ToolWindowPanel.java:374)
		at org.jetbrains.plugins.spotbugs.actions.AbstractToggleAction.update(AbstractToggleAction.java:52)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:159)
		at com.intellij.openapi.actionSystem.ex.ActionUtil$$Lambda$1328/0x0000000800df5920.run(Unknown Source)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:182)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:740)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:145)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1326/0x0000000800defb98.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:240)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1343/0x0000000800e01740.compute(Unknown Source)
		at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
		at com.intellij.openapi.progress.ProgressManager$$Lambda$1344/0x0000000800e019b0.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1318/0x0000000800dee000.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1319/0x0000000800dee248.compute(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
		at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
		at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$8(ActionUpdater.java:231)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1342/0x0000000800e014f8.invoke(Unknown Source)
		at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.computeWithSpan(trace.kt:171)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$9(ActionUpdater.java:229)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1340/0x0000000800e01068.get(Unknown Source)
		at io.opentelemetry.context.Context.lambda$wrapSupplier$8(Context.java:309)
		at io.opentelemetry.context.Context$$Lambda$1341/0x0000000800e012b0.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:47)
		at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor$$Lambda$1334/0x0000000800df2db0.run(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$21(Utils.java:823)
		at com.intellij.openapi.actionSystem.impl.Utils$$Lambda$7394/0x0000000802cd6248.run(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:876)
		at com.intellij.openapi.actionSystem.impl.Utils.runUpdateSessionForInputEvent(Utils.java:821)
		at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction$lambda$3(IdeKeyEventDispatcher.kt:548)
		at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$$Lambda$7388/0x0000000802cd2d40.compute(Unknown Source)
		at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
		at com.intellij.openapi.progress.ProgressManager$$Lambda$1344/0x0000000800e019b0.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1318/0x0000000800dee000.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1319/0x0000000800dee248.compute(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
		at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
		at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
		at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction$intellij_platform_ide_impl(IdeKeyEventDispatcher.kt:545)
		at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.processEvent(IdeMouseEventDispatcher.java:270)
		at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.dispatchMouseEvent(IdeMouseEventDispatcher.java:254)
		at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:632)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
		at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
		at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
		at com.intellij.ide.IdeEventQueueKt$$Lambda$570/0x00000008006d0000.run(Unknown Source)
		at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
		at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
		at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
		at com.intellij.ide.IdeEventQueue$$Lambda$569/0x00000008006cb410.run(Unknown Source)
		at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
		at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
		at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
		at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
		at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
	Suppressed: java.lang.Throwable: EDT-trace-at-105-ms (1/5)
		at java.desktop/sun.font.FileFontStrike._getGlyphImageFromWindows(Native Method)
		at java.desktop/sun.font.FileFontStrike.getGlyphImageFromWindows(FileFontStrike.java:410)
		at java.desktop/sun.font.FileFontStrike.getGlyphImageFromNative(FileFontStrike.java:357)
		at java.desktop/sun.font.FileFontStrike.getGlyphImagePtr(FileFontStrike.java:456)
		at java.desktop/sun.font.FileFontStrike.getGlyphAdvance(FileFontStrike.java:762)
		at java.desktop/sun.font.FileFontStrike.getGlyphAdvance(FileFontStrike.java:673)
		at java.desktop/sun.font.CompositeStrike.getGlyphAdvance(CompositeStrike.java:149)
		at java.desktop/sun.font.CompositeStrike.getCodePointAdvance(CompositeStrike.java:160)
		at java.desktop/sun.font.FontDesignMetrics.handleCharWidth(FontDesignMetrics.java:420)
		at java.desktop/sun.font.FontDesignMetrics.getLatinCharWidth(FontDesignMetrics.java:429)
		at java.desktop/sun.font.FontDesignMetrics.stringWidth(FontDesignMetrics.java:480)
		at java.desktop/sun.swing.SwingUtilities2.getFontStringWidth(SwingUtilities2.java:939)
		at java.desktop/sun.swing.SwingUtilities2.stringWidth(SwingUtilities2.java:404)
		at java.desktop/sun.swing.SwingUtilities2.stringWidth(SwingUtilities2.java:374)
		at java.desktop/javax.swing.SwingUtilities.layoutCompoundLabelImpl(SwingUtilities.java:1133)
		at java.desktop/javax.swing.SwingUtilities.layoutCompoundLabel(SwingUtilities.java:1004)
		at java.desktop/javax.swing.plaf.basic.BasicLabelUI.layoutCL(BasicLabelUI.java:108)
		at com.intellij.ide.ui.laf.darcula.ui.DarculaLabelUI.layoutCL(DarculaLabelUI.java:94)
		at java.desktop/javax.swing.plaf.basic.BasicLabelUI.getPreferredSize(BasicLabelUI.java:262)
		at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1721)
		at com.intellij.openapi.wm.impl.content.TabContentLayout.layout(TabContentLayout.java:154)
		at com.intellij.openapi.wm.impl.content.SingleContentLayout.layout(SingleContentLayout.kt:237)
		at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.update(ToolWindowContentUi.java:348)
		at com.intellij.openapi.wm.impl.content.ToolWindowContentUi$1.selectionChanged(ToolWindowContentUi.java:206)
		at jdk.internal.reflect.GeneratedMethodAccessor233.invoke(Unknown Source)
		at java.base@17.0.8/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:568)
		at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:118)
		at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:83)
		at com.intellij.util.EventDispatcher$$Lambda$451/0x000000080055f808.invoke(Unknown Source)
		at jdk.proxy2/jdk.proxy2.$Proxy188.selectionChanged(Unknown Source)
		at com.intellij.ui.content.impl.ContentManagerImpl.fireSelectionChanged(ContentManagerImpl.java:621)
		at com.intellij.ui.content.impl.ContentManagerImpl.addSelectedContent(ContentManagerImpl.java:432)
		at com.intellij.ui.content.impl.ContentManagerImpl$2.run(ContentManagerImpl.java:520)
		at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContent(ContentManagerImpl.java:536)
		at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:485)
		at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:475)
		at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:559)
		at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContent(ContentManagerImpl.java:564)
		at com.intellij.ui.content.impl.ContentManagerImpl.doAddContent(ContentManagerImpl.java:201)
		at com.intellij.ui.content.impl.ContentManagerImpl.addContent(ContentManagerImpl.java:171)
		at org.jetbrains.plugins.spotbugs.core.ToolWindowFactoryImpl.createToolWindowContent(ToolWindowFactoryImpl.java:33)
		at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:554)
		at com.intellij.openapi.wm.impl.ToolWindowImpl.getContentManager(ToolWindowImpl.kt:423)
		at org.jetbrains.plugins.spotbugs.gui.toolwindow.view.ToolWindowPanel.getInstance(ToolWindowPanel.java:374)
		at org.jetbrains.plugins.spotbugs.actions.AbstractToggleAction.update(AbstractToggleAction.java:52)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:159)
		at com.intellij.openapi.actionSystem.ex.ActionUtil$$Lambda$1328/0x0000000800df5920.run(Unknown Source)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:182)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:740)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:145)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1326/0x0000000800defb98.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:240)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1343/0x0000000800e01740.compute(Unknown Source)
		at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
		at com.intellij.openapi.progress.ProgressManager$$Lambda$1344/0x0000000800e019b0.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1318/0x0000000800dee000.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1319/0x0000000800dee248.compute(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
		at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
		at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$8(ActionUpdater.java:231)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1342/0x0000000800e014f8.invoke(Unknown Source)
		at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.computeWithSpan(trace.kt:171)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$9(ActionUpdater.java:229)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1340/0x0000000800e01068.get(Unknown Source)
		at io.opentelemetry.context.Context.lambda$wrapSupplier$8(Context.java:309)
		at io.opentelemetry.context.Context$$Lambda$1341/0x0000000800e012b0.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:47)
		at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor$$Lambda$1334/0x0000000800df2db0.run(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$21(Utils.java:823)
		at com.intellij.openapi.actionSystem.impl.Utils$$Lambda$7394/0x0000000802cd6248.run(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:876)
		at com.intellij.openapi.actionSystem.impl.Utils.runUpdateSessionForInputEvent(Utils.java:821)
		at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction$lambda$3(IdeKeyEventDispatcher.kt:548)
		at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$$Lambda$7388/0x0000000802cd2d40.compute(Unknown Source)
		at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
		at com.intellij.openapi.progress.ProgressManager$$Lambda$1344/0x0000000800e019b0.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1318/0x0000000800dee000.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1319/0x0000000800dee248.compute(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
		at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
		at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
		at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction$intellij_platform_ide_impl(IdeKeyEventDispatcher.kt:545)
		at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.processEvent(IdeMouseEventDispatcher.java:270)
		at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.dispatchMouseEvent(IdeMouseEventDispatcher.java:254)
		at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:632)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
		at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
		at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
		at com.intellij.ide.IdeEventQueueKt$$Lambda$570/0x00000008006d0000.run(Unknown Source)
		at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
		at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
		at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
		at com.intellij.ide.IdeEventQueue$$Lambda$569/0x00000008006cb410.run(Unknown Source)
		at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
		at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
		at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
		at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
		at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
