### ISSUE TITLE
Runtime Error in 1.2.7

### ISSUE THREAD

**Issue by Balaavchandran** [JetBrains/spotbugs-intellij-plugin#1596]
Hello All,

Installed latest version - 1.2.7 and tried to analysis our project and getting the below error though installation was successful . please do the needful to resolve this error, Thanks.  

java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.plugins.spotbugs.core.FindBugsProject
  at org.jetbrains.plugins.spotbugs.core.FindBugsProjects.lambda$get$0(FindBugsProjects.java:129)
  at org.jetbrains.plugins.spotbugs.common.util.WithPluginClassloader.notNull(WithPluginClassloader.java:58)
  at org.jetbrains.plugins.spotbugs.core.FindBugsProjects.get(FindBugsProjects.java:129)
  at org.jetbrains.plugins.spotbugs.actions.AnalyzeProjectFiles$1.configure(AnalyzeProjectFiles.java:116)
  at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.lambda$asyncStartImpl$3(FindBugsStarter.java:201)
  at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
  at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.asyncStartImpl(FindBugsStarter.java:200)
  at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.asyncStart(FindBugsStarter.java:190)
  at org.jetbrains.plugins.spotbugs.core.FindBugsStarter$2.run(FindBugsStarter.java:174)
  at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
  at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
  at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
  at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
  at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
  at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
  at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
  at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
  at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
  at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
  at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
  at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
  at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
  at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
  at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
  at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
  at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Balaavchandran** [comment]
Dear Team,

is there any work around to overcome this challenge - struck here for more than 3 weeks now. pls help. Thanks

**Comment by gohilmca** [comment]
> Dear Team,
> 
> is there any work around to overcome this challenge - struck here for more than 3 weeks now. pls help. Thanks

Meanwhile the technical team give fix, may be 1.2.6 will work for you, if possible then give it a try.

**Comment by Balaavchandran** [comment]
faced exact similar issue in1.2.6 as well, that's why moved to 1.2.7 without any luck. please help to resolve this outstanding challenge. Thanks
