### ISSUE TITLE
Since update to Intellij 2024.1, an error is reported for use of deprecated 'ActionUpdateThread.OLD_EDT'

### ISSUE THREAD

**Issue by ustieber** [JetBrains/spotbugs-intellij-plugin#1612]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.jetbrains.plugins.spotbugs.actions.AnalyzeSelectedFiles' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.jetbrains.plugins.spotbugs]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by fishermans** [comment]
To fix it, see https://github.com/bazelbuild/intellij/issues/5993

**Comment by Yoghesh16** [comment]
Any updates on this?

**Comment by mkeller-ergon** [comment]
Same here. And everytime it happens, IntelliJ begins to slow down considerably on every click in a file. The activity monitor then always shows the actionSystem.impl (in com.intellij.openapi) process as using 10% or more CPU (which is also seen in the stacktrace of this error) - I have to restart the IDE to get decent performance again.

**Comment by xilefton** [comment]
error still happening with IntelliJ 2024.2 and Spotbugs plugin 1.2.7

**Comment by RetGal** [comment]
Same issue with IntelliJ  2024.2.1and Spotbugs plugin 1.2.8

**Comment by fishermans** [comment]
PUSH: See https://github.com/nrayburn-tech/spotbugs-intellij-plugin/commit/88b0e5c74811cc2787cb3ca368544addea024a5b

**Comment by radkin** [comment]
Please can someone close to this work review the PR? It has been open for five months. There's even a comment that the fix is in use by people who have patched the plugin and are actively using it.
