### ISSUE TITLE
Not working properly In IDEA 2024.2 with SpotBugs version 4.7.3

### ISSUE THREAD

**Issue by xinyutian86** [JetBrains/spotbugs-intellij-plugin#1622]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.jetbrains.plugins.spotbugs.actions.AnalyzeModuleFilesNotIncludingTests' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.jetbrains.plugins.spotbugs]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by errodrigues** [comment]
Seeing exact same problem since I upgraded my IJ to 2024.x
