### ISSUE TITLE
Plugin cannot scan any classes in IntelliJ 2024.2

### ISSUE THREAD

**Issue by jonasPoehler** [JetBrains/spotbugs-intellij-plugin#1627]
When I try to scan any classes (either single class, package or hole project), I receive the following error message:
![grafik](https://github.com/user-attachments/assets/eda8686a-8141-4b51-857e-23083cf33093)

When I display the error, I get 27 very similar errors displayed (all concerning different action-classes):
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.jetbrains.plugins.spotbugs.actions.ClearAndCloseToolWindow' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.jetbrains.plugins.spotbugs]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```
Is it possible that the plugin is not compatible with 2024.2, because the older Gradle Plugin 1.x is used and 2024.2 requires 2.x or is this "simply" a breaking platform change? Source: https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#usage
If I can assist any further (provide logs, tests, etc.) I'd be happy to!

**Comment by errodrigues** [comment]
I've been having exact same issue since I upgraded to 2024.x versions of IJ
