### ISSUE TITLE
Plugin throws an error on the latest IntelliJ IDEA 2024.2.3 (Ultimate Edition)

### ISSUE THREAD

**Issue by mmesnjak** [JetBrains/spotbugs-intellij-plugin#1632]
This is the error I am receiving:

`com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.jetbrains.plugins.spotbugs.actions.AnalyzeChangelistFiles' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.jetbrains.plugins.spotbugs]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
`

If I can somehow help, please let me know.

**Comment by audio-engineer** [comment]
@mmesnjak I can confirm that I have the same issue but with another related class. It keeps popping up ~ 20 times when opening an IntelliJ window. It seems to be an issue with https://github.com/JetBrains/spotbugs-intellij-plugin/blob/master/src/main/java/org/jetbrains/plugins/spotbugs/actions/AbstractAnalyzeAction.java and all classes that inherit from it.

Here is the error again but formatted more nicely:
```text
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.jetbrains.plugins.spotbugs.actions.AnalyzeClassUnderCursor' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.jetbrains.plugins.spotbugs]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```
I too can help if needed.
