### ISSUE TITLE
Exception when trying to export HTML report

### ISSUE THREAD

**Issue by jedi10** [JetBrains/spotbugs-intellij-plugin#23]
When trying to export HTML report.

Product Infos
    SpotBugs: 4.0.3
    IntelliJ SpotBugs plugin: 1.1.1
    IDEA: IntelliJ IDEA 2019.3.3
    IDEA-Build: IU-193.6494.35, February 11, 2020
    JRE: 11.0.5+10-b520.38 amd64
    JVM: OpenJDK 64-Bit Server VM JetBrains s.r.o

java.lang.RuntimeException: javax.xml.transform.TransformerConfigurationException: file:///I:/Soft/ideaIU/jbr/bin/plain.xsl: line 280: Required attribute 'select' is missing.
	at org.jetbrains.plugins.spotbugs.common.util.ErrorUtil.toUnchecked(ErrorUtil.java:48)
	at org.jetbrains.plugins.spotbugs.actions.ExportBugCollection$1.run(ExportBugCollection.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.xml.transform.TransformerConfigurationException: file:///I:/Soft/ideaIU/jbr/bin/plain.xsl: line 280: Required attribute 'select' is missing.
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:1061)
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:817)
	at org.jetbrains.plugins.spotbugs.actions.ExportBugCollection.exportHtml(ExportBugCollection.java:198)
	at org.jetbrains.plugins.spotbugs.actions.ExportBugCollection.exportImpl(ExportBugCollection.java:174)
	at org.jetbrains.plugins.spotbugs.actions.ExportBugCollection$1.run(ExportBugCollection.java:141)
	... 15 more

**Comment by jqyp** [comment]
The problem has been fixed here: 934797d91e6495d635cf637922185a955ac0a66d
But there is another problem: #31
