### ISSUE TITLE
com.intellij.diagnostic.IdeaReportingEvent$TextBasedThrowable at com.intellij.diagnostic.IdeaReportingEvent.<init>(IdeaReportingEvent.java:18)

### ISSUE THREAD

**Issue by BlueSKySec** [JetBrains/spotbugs-intellij-plugin#26]
Hi there,

Environment: 
IntelliJ IDEA 2019.3.4 (Ultimate Edition)
Build #IU-193.6911.18, built on March 17, 2020
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2002M
Cores: 4
Registry: debugger.watches.in.variables=false, search.everywhere.toolwindows=false
Non-Bundled Plugins: Batch Scripts Support, Lombook Plugin, com.intellij.ideolog, org.jetbrains.plugins.spotbugs

I've installed Spotbugs plugin 1.1.1 incl. FindSecurityBugs .

When I run "Analyze -> Spotbugs -> Analize Project Files Not Including Test Sources" I'm getting the following exception (copied from IntelliJ):

edu.umd.cs.findbugs.ba.AnalysisException: Exeption was thrown during analysis
	at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$3(FindBugs2.java:1125)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1118)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.executeImpl(FindBugsStarter.java:324)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.asyncStartImpl(FindBugsStarter.java:214)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.asyncStart(FindBugsStarter.java:191)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter$2.run(FindBugsStarter.java:175)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: java.lang.AssertionError: Out of bounds local variable index in static com.cr.compass.maintenance.util.RedirectOut.stop()V
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$3(FindBugs2.java:1120)
	... 22 more
Caused by: java.lang.AssertionError: Out of bounds local variable index in static com.cr.compass.maintenance.util.RedirectOut.stop()V
	at com.h3xstream.findsecbugs.taintanalysis.TaintFrameModelingVisitor.setLocalVariableTaint(TaintFrameModelingVisitor.java:895)
	at com.h3xstream.findsecbugs.taintanalysis.TaintFrameModelingVisitor.taintMutableArguments(TaintFrameModelingVisitor.java:830)
	at com.h3xstream.findsecbugs.taintanalysis.TaintFrameModelingVisitor.visitInvoke(TaintFrameModelingVisitor.java:567)
	at com.h3xstream.findsecbugs.taintanalysis.TaintFrameModelingVisitor.visitINVOKESTATIC(TaintFrameModelingVisitor.java:385)
	at org.apache.bcel.generic.INVOKESTATIC.accept(INVOKESTATIC.java:86)
	at edu.umd.cs.findbugs.ba.AbstractFrameModelingVisitor.analyzeInstruction(AbstractFrameModelingVisitor.java:84)
	at com.h3xstream.findsecbugs.taintanalysis.TaintFrameModelingVisitor.analyzeInstruction(TaintFrameModelingVisitor.java:129)
	at com.h3xstream.findsecbugs.taintanalysis.TaintAnalysis.transferInstruction(TaintAnalysis.java:90)
	at com.h3xstream.findsecbugs.taintanalysis.TaintAnalysis.transferInstruction(TaintAnalysis.java:51)
	at edu.umd.cs.findbugs.ba.AbstractDataflowAnalysis.transfer(AbstractDataflowAnalysis.java:136)
	at edu.umd.cs.findbugs.ba.Dataflow.execute(Dataflow.java:378)
	at com.h3xstream.findsecbugs.taintanalysis.TaintDataflowEngine.analyze(TaintDataflowEngine.java:183)
	at com.h3xstream.findsecbugs.taintanalysis.TaintDataflowEngine.analyze(TaintDataflowEngine.java:56)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:368)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:321)
	at com.h3xstream.findsecbugs.injection.AbstractTaintDetector.getTaintDataFlow(AbstractTaintDetector.java:142)
	at com.h3xstream.findsecbugs.injection.AbstractTaintDetector.analyzeMethod(AbstractTaintDetector.java:109)
	at com.h3xstream.findsecbugs.injection.AbstractTaintDetector.visitClassContext(AbstractTaintDetector.java:79)
	at edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
	at edu.umd.cs.findbugs.FindBugs2.lambda$null$1(FindBugs2.java:1108)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at edu.umd.cs.findbugs.CurrentThreadExecutorService.execute(CurrentThreadExecutorService.java:86)
	at java.base/java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:242)
	... 21 more

The Java class where the error is happening;

package com.cr.compass.maintenance.util;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintStream;

public class RedirectOut {
	private static PrintStream originalOut;

	/** utility class */
	private RedirectOut() {
	}

	public static synchronized void start(String filename) throws FileNotFoundException {
		if (originalOut == null) {
			PrintStream currentPS = System.out;
			originalOut = currentPS;

			FileOutputStream fos = new FileOutputStream(filename);
			// OutputStreamWriter osw = new OutputStreamWriter(fos,encoding);
			// BufferedWriter bw = new BufferedWriter(osw);
			// PrintWriter pw = new PrintWriter(bw);
			PrintStream ps = new PrintStream(fos);
			System.setOut(ps);
		} else {
			throw new IllegalStateException("RedirectOut already in used");
		}
	}

	public static synchronized void stop() {

		if (originalOut != null) {
			System.setOut(originalOut);
		} else {
			throw new IllegalStateException("RedirectOut not in use");
		}
	}
}

This error occurs in a project with roughly 2K Java classes.

**Comment by amaembo** [comment]
It's a problem inside find-sec-bugs plugin. Please report it there
https://github.com/find-sec-bugs/find-sec-bugs/issues
