### ISSUE TITLE
com.intellij.openapi.progress.ProcessCanceledException at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:135)

### ISSUE THREAD

**Issue by Trumpeldor** [JetBrains/spotbugs-intellij-plugin#58]
![1](https://user-images.githubusercontent.com/62065136/100902968-10852280-34ce-11eb-97ca-686ef4a8bc2b.png)
![2](https://user-images.githubusercontent.com/62065136/100902976-11b64f80-34ce-11eb-871f-7cd98e51a821.png)

Product Infos
   SpotBugs: 4.1.3
   IntelliJ SpotBugs plugin: 1.2.4
   IDEA: IntelliJ IDEA 2020.2.4
   IDEA-Build: IU-202.8194.7, November 24, 2020
   JRE: 11.0.9+11-b944.49 amd64
   JVM: OpenJDK 64-Bit Server VM JetBrains s.r.o.

null
com.intellij.diagnostic.PluginException:  [Plugin: org.jetbrains.plugins.spotbugs]
at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:301)
at com.intellij.openapi.util.AtomicNotNullLazyValue$1.compute(AtomicNotNullLazyValue.java:59)
at com.intellij.openapi.util.AtomicNotNullLazyValue.getValue(AtomicNotNullLazyValue.java:37)
at com.intellij.openapi.options.ConfigurableEP.canCreateConfigurable(ConfigurableEP.java:362)
at com.intellij.openapi.options.ex.ConfigurableWrapper.wrapConfigurable(ConfigurableWrapper.java:32)
at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurables(ConfigurableExtensionPointUtil.java:371)
at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.lambda$getConfigurableGroup$1(ConfigurableExtensionPointUtil.java:119)
at com.intellij.openapi.util.ClearableLazyValue$2.compute(ClearableLazyValue.java:26)
at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:39)
at com.intellij.openapi.util.AtomicClearableLazyValue.getValue(AtomicClearableLazyValue.java:9)
at com.intellij.openapi.options.ex.EpBasedConfigurableGroup.<init>(EpBasedConfigurableGroup.kt:113)
at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurableGroup(ConfigurableExtensionPointUtil.java:118)
at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurables(ShowSettingsUtilImpl.java:61)
at com.intellij.ide.util.gotoByName.GotoActionModel.lambda$new$0(GotoActionModel.java:125)
at com.intellij.openapi.util.VolatileNotNullLazyValue$1.compute(VolatileNotNullLazyValue.java:56)
at com.intellij.openapi.util.VolatileNotNullLazyValue.getValue(VolatileNotNullLazyValue.java:36)
at com.intellij.ide.util.gotoByName.GotoActionModel.getConfigurablesNames(GotoActionModel.java:411)
at com.intellij.ide.util.gotoByName.GotoActionItemProvider.processOptions(GotoActionItemProvider.java:166)
at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:116)

**Comment by jqyp** [comment]
Duplicates #54
