### ISSUE TITLE
java.lang.IllegalArgumentException: Do not request resource from classloader using path with leading slash (path=/messages_en_US.xml) at com.intellij.util.lang.UrlClassLoader.findResource(UrlClassLoader.java:284)

### ISSUE THREAD

**Issue by NoahAndrews** [JetBrains/spotbugs-intellij-plugin#65]
This occurred when I clicked the link in a notifacation that disabled SpotBugs for R.java files.

Product Infos
    SpotBugs: 4.1.3
    IntelliJ SpotBugs plugin: 1.2.4
    IDEA: IntelliJ IDEA 2021.1 EAP
    IDEA-Build: IC-211.5538.20, February 4, 2021
    JRE: 11.0.10+8-b1304.1 amd64
    JVM: Dynamic Code Evolution 64-Bit Server VM JetBrains s.r.o.

java.lang.ExceptionInInitializerError
	at org.jetbrains.plugins.spotbugs.common.util.FindBugsCustomPluginUtil$1.compute(FindBugsCustomPluginUtil.java:85)
	at org.jetbrains.plugins.spotbugs.common.util.FindBugsCustomPluginUtil$1.compute(FindBugsCustomPluginUtil.java:82)
	at org.jetbrains.plugins.spotbugs.common.util.WithPluginClassloader.compute(WithPluginClassloader.java:46)
	at org.jetbrains.plugins.spotbugs.common.util.FindBugsCustomPluginUtil.loadTemporary(FindBugsCustomPluginUtil.java:82)
	at org.jetbrains.plugins.spotbugs.common.util.FindBugsCustomPluginUtil.loadTemporary(FindBugsCustomPluginUtil.java:72)
	at org.jetbrains.plugins.spotbugs.plugins.AbstractPluginLoader.load(AbstractPluginLoader.java:91)
	at org.jetbrains.plugins.spotbugs.gui.settings.PluginTablePane.load(PluginTablePane.java:280)
	at org.jetbrains.plugins.spotbugs.gui.settings.PluginTablePane.reset(PluginTablePane.java:274)
	at org.jetbrains.plugins.spotbugs.gui.settings.GeneralTab.reset(GeneralTab.java:94)
	at org.jetbrains.plugins.spotbugs.gui.settings.SettingsPane.reset(SettingsPane.java:169)
	at org.jetbrains.plugins.spotbugs.gui.settings.AbstractConfigurableImpl.reset(AbstractConfigurableImpl.java:94)
	at org.jetbrains.plugins.spotbugs.gui.settings.ProjectConfigurableImpl.reset(ProjectConfigurableImpl.java:57)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.reset(ConfigurableCardPanel.java:187)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.lambda$createConfigurableComponent$4(ConfigurableCardPanel.java:124)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:845)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.createConfigurableComponent(ConfigurableCardPanel.java:111)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.create(ConfigurableCardPanel.java:59)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:53)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:50)
	at com.intellij.ui.CardLayoutPanel.createValue(CardLayoutPanel.java:81)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:109)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:94)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor.init(ConfigurableEditor.java:102)
	at com.intellij.openapi.options.newEditor.SingleSettingEditor.<init>(SingleSettingEditor.java:29)
	at com.intellij.openapi.options.newEditor.SettingsDialog.<init>(SettingsDialog.java:47)
	at com.intellij.openapi.options.newEditor.SettingsDialogFactory.create(SettingsDialogFactory.java:24)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.editConfigurable(ShowSettingsUtilImpl.java:249)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.editConfigurable(ShowSettingsUtilImpl.java:211)
	at org.jetbrains.plugins.spotbugs.gui.settings.AbstractConfigurableImpl.showImpl(AbstractConfigurableImpl.java:117)
	at org.jetbrains.plugins.spotbugs.gui.settings.AbstractConfigurableImpl.showFileFilterAndAddRFilerFilterImpl(AbstractConfigurableImpl.java:130)
	at org.jetbrains.plugins.spotbugs.gui.settings.ProjectConfigurableImpl.showFileFilterAndAddRFilerFilter(ProjectConfigurableImpl.java:93)
	at org.jetbrains.plugins.spotbugs.android.RFilerFilterSuggestion$1.linkClicked(RFilerFilterSuggestion.java:91)
	at org.jetbrains.plugins.spotbugs.core.AbstractSuggestionNotificationListener.hyperlinkUpdate(AbstractSuggestionNotificationListener.java:69)
	at com.intellij.notification.impl.ui.NotificationsUtil$1.hyperlinkUpdate(NotificationsUtil.java:168)
	at java.desktop/javax.swing.JEditorPane.fireHyperlinkUpdate(JEditorPane.java:345)
	at java.desktop/javax.swing.text.html.HTMLEditorKit$LinkController.activateLink(HTMLEditorKit.java:899)
	at java.desktop/javax.swing.text.html.HTMLEditorKit$LinkController.mouseClicked(HTMLEditorKit.java:695)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:277)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:277)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6655)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:972)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:835)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:448)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:783)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:782)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: Do not request resource from classloader using path with leading slash (path=/messages_en_US.xml)
	at com.intellij.util.lang.UrlClassLoader.findResource(UrlClassLoader.java:284)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:383)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
	at edu.umd.cs.findbugs.PluginLoader.getResource(PluginLoader.java:560)
	at edu.umd.cs.findbugs.PluginLoader.addCollection(PluginLoader.java:1279)
	at edu.umd.cs.findbugs.PluginLoader.getMessageDocuments(PluginLoader.java:1187)
	at edu.umd.cs.findbugs.PluginLoader.init(PluginLoader.java:690)
	at edu.umd.cs.findbugs.PluginLoader.<init>(PluginLoader.java:395)
	at edu.umd.cs.findbugs.PluginLoader.loadCorePlugin(PluginLoader.java:1442)
	at edu.umd.cs.findbugs.PluginLoader.loadInitialPlugins(PluginLoader.java:1396)
	at edu.umd.cs.findbugs.PluginLoader.<clinit>(PluginLoader.java:149)
	... 79 more

**Comment by amaembo** [comment]
Duplicates #65

**Comment by NoahAndrews** [comment]
I think you linked the wrong issue. This is #65

**Comment by amaembo** [comment]
Should be #66, sorry.
