### ISSUE TITLE
Do not request resource from classloader using path with leading slash

### ISSUE THREAD

**Issue by winhkey** [JetBrains/spotbugs-intellij-plugin#76]
Product Infos
    SpotBugs: 4.1.3
    IntelliJ SpotBugs plugin: 1.2.4
    IDEA: IntelliJ IDEA 2021.1 Beta
    IDEA-Build: IU-211.6305.21, March 5, 2021
    JRE: 11.0.10+9-b1341.18 amd64
    JVM: Dynamic Code Evolution 64-Bit Server VM JetBrains s.r.o.

Do not request resource from classloader using path with leading slash
com.intellij.diagnostic.PluginException: /messages_zh_CN.xml [Plugin: org.jetbrains.plugins.spotbugs]
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:410)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:376)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
	at edu.umd.cs.findbugs.PluginLoader.getResource(PluginLoader.java:560)
	at edu.umd.cs.findbugs.PluginLoader.addCollection(PluginLoader.java:1279)
	at edu.umd.cs.findbugs.PluginLoader.getMessageDocuments(PluginLoader.java:1187)
	at edu.umd.cs.findbugs.PluginLoader.init(PluginLoader.java:690)
	at edu.umd.cs.findbugs.PluginLoader.<init>(PluginLoader.java:395)
	at edu.umd.cs.findbugs.PluginLoader.loadCorePlugin(PluginLoader.java:1442)
	at edu.umd.cs.findbugs.PluginLoader.loadInitialPlugins(PluginLoader.java:1396)
	at edu.umd.cs.findbugs.PluginLoader.<clinit>(PluginLoader.java:149)
	at org.jetbrains.plugins.spotbugs.common.util.FindBugsCustomPluginUtil$1.compute(FindBugsCustomPluginUtil.java:85)
	at org.jetbrains.plugins.spotbugs.common.util.FindBugsCustomPluginUtil$1.compute(FindBugsCustomPluginUtil.java:82)
	at org.jetbrains.plugins.spotbugs.common.util.WithPluginClassloader.compute(WithPluginClassloader.java:46)
	at org.jetbrains.plugins.spotbugs.common.util.FindBugsCustomPluginUtil.loadTemporary(FindBugsCustomPluginUtil.java:82)
	at org.jetbrains.plugins.spotbugs.common.util.FindBugsCustomPluginUtil.loadTemporary(FindBugsCustomPluginUtil.java:72)
	at org.jetbrains.plugins.spotbugs.plugins.AbstractPluginLoader.load(AbstractPluginLoader.java:91)
	at org.jetbrains.plugins.spotbugs.gui.settings.PluginTablePane.load(PluginTablePane.java:280)
	at org.jetbrains.plugins.spotbugs.gui.settings.PluginTablePane.reset(PluginTablePane.java:274)
	at org.jetbrains.plugins.spotbugs.gui.settings.GeneralTab.reset(GeneralTab.java:94)
	at org.jetbrains.plugins.spotbugs.gui.settings.SettingsPane.reset(SettingsPane.java:169)
	at org.jetbrains.plugins.spotbugs.gui.settings.AbstractConfigurableImpl.reset(AbstractConfigurableImpl.java:94)
	at org.jetbrains.plugins.spotbugs.gui.settings.ModuleConfigurableImpl.reset(ModuleConfigurableImpl.java:57)
	at com.intellij.openapi.roots.ui.configuration.ModuleConfigurableWrapper.reset(ModuleConfigurableWrapper.java:58)
	at com.intellij.openapi.roots.ui.configuration.TabbedModuleEditor.createCenterPanel(TabbedModuleEditor.java:63)
	at com.intellij.openapi.roots.ui.configuration.HeaderHidingTabbedModuleEditor.createCenterPanel(HeaderHidingTabbedModuleEditor.java:30)
	at com.intellij.openapi.roots.ui.configuration.ModuleEditor.createPanel(ModuleEditor.java:247)
	at com.intellij.openapi.roots.ui.configuration.ModuleEditor.getPanel(ModuleEditor.java:259)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ModuleConfigurable.createOptionsPanel(ModuleConfigurable.java:122)
	at com.intellij.openapi.ui.NamedConfigurable.createComponent(NamedConfigurable.java:73)
	at com.intellij.openapi.ui.MasterDetailsComponent.updateSelection(MasterDetailsComponent.java:596)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ModuleStructureConfigurable.updateSelection(ModuleStructureConfigurable.java:195)
	at com.intellij.openapi.ui.MasterDetailsComponent.setSelectedNode(MasterDetailsComponent.java:587)
	at com.intellij.openapi.ui.MasterDetailsComponent.updateSelectionFromTree(MasterDetailsComponent.java:225)
	at com.intellij.openapi.ui.MasterDetailsComponent.createComponent(MasterDetailsComponent.java:279)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ModuleStructureConfigurable.createComponent(ModuleStructureConfigurable.java:418)
	at com.intellij.openapi.roots.ui.configuration.ProjectStructureConfigurable.navigateTo(ProjectStructureConfigurable.java:512)
	at com.intellij.openapi.roots.ui.configuration.ProjectStructureConfigurable.reset(ProjectStructureConfigurable.java:356)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.reset(ConfigurableCardPanel.java:187)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.lambda$createConfigurableComponent$4(ConfigurableCardPanel.java:124)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:844)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.createConfigurableComponent(ConfigurableCardPanel.java:111)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.create(ConfigurableCardPanel.java:59)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:53)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:50)
	at com.intellij.ui.CardLayoutPanel.createValue(CardLayoutPanel.java:83)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:111)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:96)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor.init(ConfigurableEditor.java:102)
	at com.intellij.openapi.options.newEditor.SingleSettingEditor.<init>(SingleSettingEditor.java:29)
	at com.intellij.openapi.options.newEditor.SettingsDialog.<init>(SettingsDialog.java:47)
	at com.intellij.openapi.options.newEditor.SettingsDialogFactory.create(SettingsDialogFactory.java:24)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.editConfigurable(ShowSettingsUtilImpl.java:249)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.editConfigurable(ShowSettingsUtilImpl.java:211)
	at com.intellij.openapi.roots.ui.configuration.ModulesConfigurator.showDialog(ModulesConfigurator.java:559)
	at com.intellij.openapi.roots.ui.configuration.IdeaProjectSettingsService.openContentEntriesSettings(IdeaProjectSettingsService.java:90)
	at com.android.tools.idea.gradle.structure.AndroidProjectSettingsServiceImpl.openContentEntriesSettings(AndroidProjectSettingsServiceImpl.java:209)
	at com.intellij.ide.projectView.impl.nodes.PsiDirectoryNode.navigate(PsiDirectoryNode.java:298)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:83)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:58)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:51)
	at com.intellij.util.OpenSourceUtil.openSourcesFrom(OpenSourceUtil.java:19)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.processDoubleClick(EditSourceOnDoubleClickHandler.java:166)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.onDoubleClick(EditSourceOnDoubleClickHandler.java:160)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:392)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:45)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by jqyp** [comment]
Duplicates #66
