### ISSUE TITLE
NPE at com.intellij.util.SVGLoader.loadFromClassResource(SVGLoader.java:165)

### ISSUE THREAD

**Issue by soberich** [JetBrains/spotbugs-intellij-plugin#88]
Product Infos
    SpotBugs: 4.1.3
    IntelliJ SpotBugs plugin: 1.2.4
    IDEA: IntelliJ IDEA 2021.1.2 RC
    IDEA-Build: IU-211.7442.27, May 25, 2021
    JRE: 11.0.11+9-b1341.57 x86_64
    JVM: Dynamic Code Evolution 64-Bit Server VM JetBrains s.r.o.

java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.openapi.util.IconLoader.getReflectiveIcon(IconLoader.java:174)
	at com.intellij.openapi.util.IconLoader.findIcon(IconLoader.java:360)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.setIconFromClass(ActionManagerImpl.java:299)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.updateIconFromStub(ActionManagerImpl.java:266)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:226)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:551)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1601)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:14)
	at com.intellij.openapi.application.Preloader.lambda$preload$0(Preloader.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.application.Preloader.lambda$preload$1(Preloader.java:74)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at com.intellij.util.SVGLoader.loadFromClassResource(SVGLoader.java:165)
	at com.intellij.util.ImageLoader.loadByDescriptorWithoutCache(ImageLoader.java:273)
	at com.intellij.util.ImageLoader.loadByDescriptor(ImageLoader.java:227)
	at com.intellij.util.ImageLoader.loadImage(ImageLoader.java:152)
	at com.intellij.openapi.util.IconLoader$ImageDataResolverImpl.loadImage(IconLoader.java:1173)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.loadImage(IconLoader.java:936)
	at com.intellij.openapi.util.IconLoader$ScaledIconCache.getOrScaleIcon(IconLoader.java:1005)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getRealIcon(IconLoader.java:824)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getIconWidth(IconLoader.java:752)
	at com.intellij.ui.LayeredIcon.updateSize(LayeredIcon.java:281)
	at com.intellij.ui.LayeredIcon.setIcon(LayeredIcon.java:151)
	at com.intellij.ui.LayeredIcon.setIcon(LayeredIcon.java:126)
	at com.intellij.ui.LayeredIcon.create(LayeredIcon.java:307)
	at icons.PluginIcons.<clinit>(PluginIcons.java:45)
	... 29 more

**Comment by soberich** [comment]
I guess this is obsolete
